window.getLovePokeTournamentParticipants=()=>Array.from({length:pokeState.players},(_,pi)=>({
  id:DEFAULT_PLAYERS[pi]?.playerId||`player-slot-${pi+1}`,
  playerId:DEFAULT_PLAYERS[pi]?.playerId||`player-slot-${pi+1}`,
  name:playerDisplayName(pi),
  displayName:playerDisplayName(pi),
  pokemon:Array.from(
    {length:pokeState.perPlayer},
    (_,slot)=>pokeState.manualPokemon[pi]?.[slot]||pokeState.groups[pi]?.[slot]
  )
    .filter(Boolean)
    .map(p=>({
      id:p.id||null,
      name:p.name,
      formKey:p.formKey||''
    }))
}));

window.getLovePokeBasePlayers=()=>DEFAULT_PLAYERS.map((p,i)=>({
  ...p,
  displayName:playerDisplayName(i)
}));