import {getFirebaseContext} from './firebase-client.js';
const $=s=>document.querySelector(s),esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),uid=()=>crypto.randomUUID?.()||Date.now()+'-'+Math.random().toString(16).slice(2);
const today=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return d.getFullYear()+'-'+p(d.getMonth()+1)+'-'+p(d.getDate())};
let cloud,players=[],matches=[],winner='',editingId=null;
function showPane(n='calculator'){const target=$('#love'+n[0].toUpperCase()+n.slice(1)+'Pane');if(!target)return;const nav=target.parentElement?.querySelector(':scope > nav.poke-subnav');nav?.querySelectorAll(':scope > .love-tab').forEach(x=>x.classList.toggle('active',x.dataset.lovePane===n));for(const pane of ['calculator','record','stats'])$('#love'+pane[0].toUpperCase()+pane.slice(1)+'Pane')?.classList.toggle('hidden',pane!==n);}
window.showLoveCaPane=showPane;
document.querySelectorAll('.love-tab[data-love-pane="calculator"],.love-tab[data-love-pane="record"],.love-tab[data-love-pane="stats"]').forEach(b=>b.onclick=()=>showPane(b.dataset.lovePane));
const status=(k,t,x)=>{$('#lovecaCloudBadge').className='badge '+k;$('#lovecaCloudBadge').textContent=t;$('#lovecaCloudText').textContent=x};
const popt=(sel='')=>'<option value="">選択</option>'+players.map(p=>`<option value="${esc(p.id)}" ${p.id===sel?'selected':''}>${esc(p.name)}</option>`).join('');
const dopt=(pid,sel='')=>'<option value="">選択</option>'+((players.find(p=>p.id===pid)?.decks)||[]).map(d=>`<option value="${esc(d.id)}" ${d.id===sel?'selected':''}>${esc(d.name)}</option>`).join('');
function setup(){const r=$('#lovecaPlayerSetup');r.innerHTML=players.map(p=>`<article class="loveca-player-config" data-pid="${p.id}"><div class="loveca-config-head"><input class="pname" value="${esc(p.name)}"><button class="danger-btn delp">削除</button></div>${(p.decks||[]).map(d=>`<div class="loveca-deck-edit"><input data-did="${d.id}" value="${esc(d.name)}"><button class="danger-btn deld" data-did="${d.id}">×</button></div>`).join('')}<button class="ghost-btn addd">デッキ追加</button></article>`).join('')||'<p class="note">プレイヤーを登録してください。</p>';
r.querySelectorAll('.pname').forEach(i=>i.onchange=async()=>{const p=players.find(x=>x.id===i.closest('[data-pid]').dataset.pid);p.name=i.value.trim()||p.name;await cloud.sp(p)});
r.querySelectorAll('input[data-did]').forEach(i=>i.onchange=async()=>{const p=players.find(x=>x.id===i.closest('[data-pid]').dataset.pid),d=p.decks.find(x=>x.id===i.dataset.did);d.name=i.value.trim()||d.name;await cloud.sp(p)});
r.querySelectorAll('.addd').forEach(b=>b.onclick=async()=>{const p=players.find(x=>x.id===b.closest('[data-pid]').dataset.pid),n=prompt('デッキ名');if(n?.trim()){p.decks=[...(p.decks||[]),{id:uid(),name:n.trim()}];await cloud.sp(p)}});
r.querySelectorAll('.deld').forEach(b=>b.onclick=async()=>{const p=players.find(x=>x.id===b.closest('[data-pid]').dataset.pid);if(confirm('デッキ登録を削除しますか？ 過去戦績は残ります。')){p.decks=p.decks.filter(d=>d.id!==b.dataset.did);await cloud.sp(p)}});
r.querySelectorAll('.delp').forEach(b=>b.onclick=async()=>{if(confirm('プレイヤー登録を削除しますか？ 過去戦績は残ります。'))await cloud.rp(b.closest('[data-pid]').dataset.pid)})}
function deck(s,sel=''){const p=$('#lovecaPlayer'+s).value;$('#lovecaDeck'+s).innerHTML=dopt(p,sel)}
function selectors(){for(const s of ['A','B']){const e=$('#lovecaPlayer'+s),v=e.value;e.innerHTML=popt(v);if(players.some(p=>p.id===v))e.value=v;deck(s)}const e=$('#lovecaStatsPlayer'),v=e.value;e.innerHTML=popt(v);if(players.some(p=>p.id===v))e.value=v}
$('#lovecaPlayerA').onchange=()=>deck('A');$('#lovecaPlayerB').onchange=()=>deck('B');
$('#addLovecaPlayer').onclick=async()=>{const n=prompt('プレイヤー名');if(n?.trim())await cloud.sp({id:uid(),name:n.trim(),decks:[],createdAt:new Date().toISOString()})};
function win(s){winner=s;$('#lovecaWinnerA').classList.toggle('active',s==='A');$('#lovecaWinnerB').classList.toggle('active',s==='B')}$('#lovecaWinnerA').onclick=()=>win('A');$('#lovecaWinnerB').onclick=()=>win('B');
function reset(){editingId=null;winner='';$('#lovecaMatchDate').value=today();for(const s of ['A','B']){$('#lovecaPlayer'+s).value='';deck(s);$('#lovecaAccident'+s).value='';$('#lovecaMemo'+s).value=''}win('');$('#saveLovecaMatch').textContent='対戦結果を保存';$('#cancelLovecaEdit').classList.add('hidden')}
const side=s=>{const pid=$('#lovecaPlayer'+s).value,did=$('#lovecaDeck'+s).value,p=players.find(x=>x.id===pid),d=p?.decks?.find(x=>x.id===did);return{playerId:pid,playerName:p?.name||'',deckId:did,deckName:d?.name||'',result:winner===s?'win':'loss',accident:$('#lovecaAccident'+s).value.trim(),memo:$('#lovecaMemo'+s).value.trim()}};
$('#saveLovecaMatch').onclick=async()=>{const a=side('A'),b=side('B');if(!a.playerId||!b.playerId||a.playerId===b.playerId)return alert('異なる2人を選択してください。');if(!a.deckId||!b.deckId)return alert('両方のデッキを選択してください。');if(!winner)return alert('○×を選択してください。');const old=matches.find(m=>m.id===editingId);await cloud.sm({id:editingId||uid(),date:$('#lovecaMatchDate').value||today(),players:[a,b],createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()});reset()};$('#cancelLovecaEdit').onclick=reset;
const entries=()=>matches.flatMap(m=>m.players.map((p,i)=>({...p,date:m.date,matchId:m.id,opp:m.players[1-i]}))),pct=(w,g)=>g?(w/g*100).toFixed(1)+'%':'—';
function render(){const es=entries();$('#lovecaMatchCount').textContent=matches.length+'戦';$('#lovecaOverallStats').innerHTML='<div class="career-grid">'+players.map(p=>{const x=es.filter(e=>e.playerId===p.id),w=x.filter(e=>e.result==='win').length;return `<article class="career-card"><h3>${esc(p.name)}</h3><div>${w}勝 ${x.length-w}敗 ／ 勝率 <b>${pct(w,x.length)}</b></div></article>`}).join('')+'</div>';
let ds=[];players.forEach(p=>(p.decks||[]).forEach(d=>{const x=es.filter(e=>e.playerId===p.id&&e.deckId===d.id),w=x.filter(e=>e.result==='win').length;if(x.length)ds.push(`<article class="career-card"><h3>${esc(p.name)} ／ ${esc(d.name)}</h3><div>${w}勝 ${x.length-w}敗 ／ 勝率 <b>${pct(w,x.length)}</b></div></article>`)}));$('#lovecaDeckStats').innerHTML='<div class="career-grid">'+ds.join('')+'</div>';h2h();
$('#lovecaMatchHistory').innerHTML=matches.map(m=>{const a=m.players[0],b=m.players[1],aw=a.result==='win';return `<article class="mahjong-history-card loveca-history-card"><strong class="loveca-history-date">${esc(m.date)}</strong><div class="loveca-history-result"><span class="${aw?'win':'loss'}">${aw?'○':'×'} ${esc(a.playerName)}</span><span class="vs">vs</span><span class="${aw?'loss':'win'}">${aw?'×':'○'} ${esc(b.playerName)}</span></div><div class="loveca-history-decks"><span>${esc(a.deckName)}</span><span>${esc(b.deckName)}</span></div><div class="loveca-history-notes">${[a,b].map(p=>(p.accident||p.memo)?`<div class="loveca-history-note"><b>${esc(p.playerName)}</b>${p.accident?`<div><span>事故</span>${esc(p.accident)}</div>`:''}${p.memo?`<div><span>メモ</span>${esc(p.memo)}</div>`:''}</div>`:'').join('')}</div><div class="history-actions"><button class="ghost-btn" data-le="${m.id}">編集</button><button class="danger-btn" data-ld="${m.id}">削除</button></div></article>`}).join('')||'<p class="note">記録はありません。</p>';document.querySelectorAll('[data-le]').forEach(b=>b.onclick=()=>edit(b.dataset.le));document.querySelectorAll('[data-ld]').forEach(b=>b.onclick=async()=>{if(confirm('削除しますか？'))await cloud.rm(b.dataset.ld)})}
function h2h(){const id=$('#lovecaStatsPlayer').value;if(!id){$('#lovecaH2hStats').innerHTML='<p class="note">プレイヤーを選択してください。</p>';return}const map=new Map();entries().filter(e=>e.playerId===id).forEach(e=>{const k=e.opp.playerId+'::'+e.opp.deckId;if(!map.has(k))map.set(k,{n:e.opp.playerName,d:e.opp.deckName,g:0,w:0});const s=map.get(k);s.g++;if(e.result==='win')s.w++});$('#lovecaH2hStats').innerHTML=[...map.values()].map(s=>`<article class="career-card"><h3>vs ${esc(s.n)} ／ ${esc(s.d)}</h3><div>${s.w}勝 ${s.g-s.w}敗 ／ 勝率 <b>${pct(s.w,s.g)}</b></div></article>`).join('')||'<p class="note">記録はありません。</p>'}$('#lovecaStatsPlayer').onchange=h2h;
function edit(id){const m=matches.find(x=>x.id===id);editingId=id;$('#lovecaMatchDate').value=m.date;['A','B'].forEach((s,i)=>{const p=m.players[i];$('#lovecaPlayer'+s).value=p.playerId;deck(s,p.deckId);$('#lovecaAccident'+s).value=p.accident||'';$('#lovecaMemo'+s).value=p.memo||''});win(m.players[0].result==='win'?'A':'B');$('#saveLovecaMatch').textContent='編集内容を保存';$('#cancelLovecaEdit').classList.remove('hidden');document.querySelector('[data-love-pane="record"]').click()}
async function init(){reset();try{const {db,firestore:{collection,onSnapshot,setDoc,doc}}=await getFirebaseContext(),ref=doc(collection(db,'tournaments'),'loveca-shared-records');const persist=()=>setDoc(ref,{kind:'lovecaRecords',schemaVersion:1,players,matches,updatedAt:new Date().toISOString()});cloud={sp:async p=>{const i=players.findIndex(x=>x.id===p.id);if(i>=0)players[i]=p;else players.push(p);await persist()},rp:async id=>{players=players.filter(p=>p.id!==id);await persist()},sm:async m=>{const i=matches.findIndex(x=>x.id===m.id);if(i>=0)matches[i]=m;else matches.push(m);await persist()},rm:async id=>{matches=matches.filter(m=>m.id!==id);await persist()}};onSnapshot(ref,s=>{const data=s.exists()?s.data():{};players=Array.isArray(data.players)?data.players:[];matches=(Array.isArray(data.matches)?data.matches:[]).sort((a,b)=>(b.date+b.createdAt).localeCompare(a.date+a.createdAt));setup();selectors();render();status('ok','同期中','全員でリアルタイム共有されています。')},e=>status('warn','同期エラー',e.message))}catch(e){status('warn','接続エラー',e.message)}}init();