import {getFirebaseContext} from './firebase-client.js';
const $=s=>document.querySelector(s),SCHEMA_VERSION=1;let cloud=null,matches=[],editingId=null,guests=[];
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`,esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`},type=()=>document.querySelector('[name="mahjongType"]:checked').value,required=()=>type()==='sanma'?3:4,basePlayers=()=>window.getLovePokeBasePlayers?.()||[],allChoices=()=>[...basePlayers(),...guests],selected=()=>[...document.querySelectorAll('[data-mahjong-player]:checked')].map(x=>allChoices().find(p=>p.playerId===x.value)).filter(Boolean);
function status(k,t,x){$('#mahjongCloudBadge').className=`badge ${k}`;$('#mahjongCloudBadge').textContent=t;$('#mahjongCloudText').textContent=x}
function normalize(raw){if(!raw||Number(raw.schemaVersion||1)>SCHEMA_VERSION)return null;return {...raw,schemaVersion:SCHEMA_VERSION,players:(raw.players||[]).map(p=>({...p,displayName:p.displayName||p.name||'',finalPoints:Number(p.finalPoints)||0,rank:Number(p.rank)||0}))}}
function renderChoices(ids=[]){$('#mahjongPlayerChoices').innerHTML=allChoices().map(p=>`<label class="mahjong-choice"><input type="checkbox" data-mahjong-player value="${esc(p.playerId)}" ${ids.includes(p.playerId)?'checked':''}><span>${esc(p.displayName)}</span></label>`).join('');document.querySelectorAll('[data-mahjong-player]').forEach(x=>x.onchange=renderResultInputs);renderResultInputs()}
function renderResultInputs(saved=[]){const ps=selected(),prior=new Map(saved.map(p=>[p.playerId,p]));$('#mahjongSelectionHint').textContent=`${type()==='sanma'?'三麻は3人':'四麻は4人'}を選択（現在 ${ps.length}人）`;$('#mahjongResultInputs').innerHTML=ps.map(p=>{const o=prior.get(p.playerId);return `<div class="mahjong-result" data-result-player="${esc(p.playerId)}"><strong>${esc(p.displayName)}</strong><label>順位<select><option value="">選択</option>${Array.from({length:required()},(_,i)=>`<option value="${i+1}" ${o?.rank===i+1?'selected':''}>${i+1}位</option>`).join('')}</select></label><label>最終持ち点<input type="number" inputmode="numeric" step="1" value="${o?.finalPoints??''}" placeholder="例：42300"></label></div>`}).join('')}
function resetForm(){editingId=null;guests=[];$('#mahjongDate').value=today();document.querySelector('[name="mahjongType"][value="sanma"]').checked=true;$('#saveMahjongMatch').textContent='対局結果を保存';$('#cancelMahjongEdit').classList.add('hidden');renderChoices()}
document.querySelectorAll('.mahjong-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mahjong-tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.mahjong-pane').forEach(x=>x.classList.add('hidden'));$(`#mahjong${b.dataset.mahjongPane[0].toUpperCase()}${b.dataset.mahjongPane.slice(1)}Pane`).classList.remove('hidden')});document.querySelectorAll('[name="mahjongType"]').forEach(x=>x.onchange=()=>renderResultInputs());
$('#addMahjongGuest').onclick=()=>{const n=$('#mahjongGuestName').value.trim();if(!n)return;guests.push({playerId:`guest-${uid()}`,displayName:n});$('#mahjongGuestName').value='';renderChoices()};$('#cancelMahjongEdit').onclick=resetForm;
$('#saveMahjongMatch').onclick=async()=>{if(!cloud)return alert('先にFirebase設定を完了してください。');const ps=selected();if(ps.length!==required())return alert(`${required()}人を選択してください。`);const rows=[...document.querySelectorAll('[data-result-player]')];if(rows.some(r=>r.querySelector('input').value.trim()===''))return alert('全員の最終持ち点を入力してください。');const results=rows.map(r=>({playerId:r.dataset.resultPlayer,displayName:ps.find(p=>p.playerId===r.dataset.resultPlayer).displayName,rank:Number(r.querySelector('select').value),finalPoints:Number(r.querySelector('input').value)}));if(results.some(p=>!p.rank||!Number.isInteger(p.finalPoints)))return alert('全員の順位と整数の最終持ち点を入力してください。');if(new Set(results.map(p=>p.rank)).size!==results.length)return alert('同じ順位は設定できません。');const old=matches.find(m=>m.id===editingId),id=editingId||uid(),match={schemaVersion:SCHEMA_VERSION,id,date:$('#mahjongDate').value||today(),type:type(),players:results,createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};try{await cloud.save(match);resetForm()}catch(e){alert(`保存できませんでした：${e.message}`)}};
function aggregate(filter){const map=new Map();matches.filter(filter).forEach(m=>m.players.forEach(p=>{if(!map.has(p.playerId))map.set(p.playerId,{name:p.displayName,games:0,ranks:[],counts:[0,0,0,0]});const s=map.get(p.playerId);s.name=p.displayName;s.games++;s.ranks.push(p.rank);s.counts[p.rank-1]++}));return map}function statsBlock(title,filter,max){const a=[...aggregate(filter).values()];return `<h3>${title}</h3><div class="career-grid">${a.map(s=>`<article class="career-card"><h3>${esc(s.name)}</h3><div>${s.games}局 ／ ${s.counts.slice(0,max).map((n,i)=>`${i+1}位 ${n}回`).join('・')}</div><div>1位率 ${(s.counts[0]/s.games*100).toFixed(1)}% ／ 平均順位 ${(s.ranks.reduce((a,b)=>a+b,0)/s.games).toFixed(2)}位</div></article>`).join('')||'<p class="note">記録はありません。</p>'}</div>`}
function render(){$('#mahjongMatchCount').textContent=`${matches.length}局`;$('#mahjongStats').innerHTML=statsBlock('三麻成績',m=>m.type==='sanma',3)+statsBlock('四麻成績',m=>m.type==='yonma',4)+statsBlock('両方合計（参考）',()=>true,4);const names=new Map();matches.forEach(m=>m.players.forEach(p=>names.set(p.playerId,p.displayName)));const sel=$('#mahjongH2hPlayer'),old=sel.value;sel.innerHTML='<option value="">プレイヤーを選択</option>'+[...names].map(([id,n])=>`<option value="${esc(id)}">${esc(n)}</option>`).join('');if(names.has(old))sel.value=old;renderH2h();$('#mahjongHistory').innerHTML=matches.map(m=>`<article class="mahjong-history-card"><strong>${esc(m.date)} ${m.type==='sanma'?'三麻':'四麻'}</strong>${[...m.players].sort((a,b)=>a.rank-b.rank).map(p=>`<div>${p.rank}位 ${esc(p.displayName)} <b>${p.finalPoints.toLocaleString('ja-JP')}点</b></div>`).join('')}<div class="history-actions"><button data-edit-match="${m.id}" class="ghost-btn">編集</button><button data-delete-match="${m.id}" class="danger-btn">削除</button></div></article>`).join('')||'<p class="note">過去の対局はありません。</p>';document.querySelectorAll('[data-edit-match]').forEach(b=>b.onclick=()=>editMatch(b.dataset.editMatch));document.querySelectorAll('[data-delete-match]').forEach(b=>b.onclick=async()=>{const m=matches.find(x=>x.id===b.dataset.deleteMatch);if(confirm(`${m.date}の対局を削除しますか？`))await cloud.remove(m.id)})}
function editMatch(id){const m=matches.find(x=>x.id===id);editingId=id;guests=m.players.filter(p=>!basePlayers().some(x=>x.playerId===p.playerId)).map(p=>({playerId:p.playerId,displayName:p.displayName}));document.querySelector(`[name="mahjongType"][value="${m.type}"]`).checked=true;$('#mahjongDate').value=m.date;renderChoices(m.players.map(p=>p.playerId));renderResultInputs(m.players);$('#saveMahjongMatch').textContent='編集内容を保存';$('#cancelMahjongEdit').classList.remove('hidden');document.querySelector('[data-mahjong-pane="entry"]').click()}
function renderH2h(){const id=$('#mahjongH2hPlayer').value;if(!id){$('#mahjongH2h').innerHTML='<p class="note">プレイヤーを選択してください。</p>';return}const map=new Map();matches.forEach(m=>{const me=m.players.find(p=>p.playerId===id);if(!me)return;m.players.filter(p=>p.playerId!==id).forEach(o=>{if(!map.has(o.playerId))map.set(o.playerId,{name:o.displayName,games:0,ranks:[],above:0,below:0});const s=map.get(o.playerId);s.games++;s.ranks.push(me.rank);if(me.rank<o.rank)s.above++;else s.below++})});$('#mahjongH2h').innerHTML=[...map.values()].map(s=>`<article class="career-card"><h3>${esc(s.name)}</h3><div>同卓 ${s.games}回 ／ 平均順位 ${(s.ranks.reduce((a,b)=>a+b,0)/s.games).toFixed(2)}位</div><div>相手より上 ${s.above}回 ／ 下 ${s.below}回</div></article>`).join('')||'<p class="note">同卓記録はありません。</p>'}$('#mahjongH2hPlayer').onchange=renderH2h;
async function init(){if(!window.LOVEPOKE_FIREBASE_CONFIG){status('warn','未設定','Firebase設定後に全端末で共有できます。');$('#saveMahjongMatch').disabled=true;return}try{const {db,firestore:{collection,onSnapshot,setDoc,doc,deleteDoc}}=await getFirebaseContext(),ref=collection(db,'mahjongMatches');cloud={save:m=>setDoc(doc(ref,m.id),m),remove:id=>deleteDoc(doc(ref,id))};onSnapshot(ref,s=>{matches=s.docs.map(d=>normalize(d.data())).filter(Boolean).sort((a,b)=>(b.date+b.createdAt).localeCompare(a.date+a.createdAt));render();status('ok','同期中','麻雀戦歴はリアルタイム同期されています。')},e=>status('warn','同期エラー',e.message))}catch(e){status('warn','接続エラー',e.message)}}resetForm();render();init();
